MediCo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MediCo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^RapidReferral/', include('RapidReferral.urls', namespace='RapidReferral')),
    url(r'^admin/', include(admin.site.urls)),
)

RapidReferral/urls.py
from django.conf.urls import include, patterns, url
from RapidReferral import views


doctors_patterns = patterns('',

    # /RapidReferral/doctors/
    url(r'^$', views.doctors, name='doctors'),
    
    # /RapidReferral/doctors/1/
    url(r'^(?P<doctor_id>\d+)/$', views.doctor_detail, name='doctor_detail'),
    
    #/RapidReferral/doctors/create/
    url(r'^create/$', views.doctor_entry, name='doctor_entry'),

)    

patients_patterns = patterns('',
    
    # /RapidReferral/patients/
    url(r'^$', views.patients, name='patients'),
    
    # /RapidReferral/patients/1/
    url(r'^(?P<patient_id>\d+)/$', views.patient_detail, name='patient_detail'),
    
    #/RapidReferral/patients/create/
    url(r'^create/$', views.patient_entry, name='patient_entry'),
    
)

offices_patterns = patterns('',
    
    # /RapidReferral/offices/
    url(r'^$', views.offices, name='offices'),
    
    # /RapidReferral/offices/1/
    url(r'^(?P<office_id>\d+)/$', views.office_detail, name='office_detail'),
    
    #/RapidReferral/offices/create/
    url(r'^create/$', views.office_entry, name='office_entry'),
    
    # /RapidReferral/offices/JSON
    url(r'^(?P<format>\w+)/$', views.offices, name='offices_formatted')
    
)

appointments_patterns = patterns('',
    
    # /RapidReferral/appointments/
    url(r'^$', views.appointments, name='appointments'),
    
    # /RapidRederral/appointments/1/
    url(r'^(?P<appointment_id>\d+)/$', views.appointment_detail, name='appointment_detail'),
    
    #/RapidReferral/appointment/create/
    url(r'^create/$', views.appointment_entry, name='appointment_entry'),
    
)


urlpatterns = patterns('',

    # /RapidReferral/
    url(r'^$', views.index, name='index'),
    
    # /RapidReferral/doctors/...
    url(r'^doctors/', include(doctors_patterns)), 
    
    # /RapidReferral/patients/...
    url(r'^patients/', include(patients_patterns)), 
    
    # /RapidReferral/offices/...
    url(r'^offices/', include(offices_patterns)), 
    
    # /RapidReferral/appointments/...
    url(r'^appointments/', include(appointments_patterns)), 
    
)


    

RapidReferral/models.py
from django.db import models
from django import forms
from django.core.urlresolvers import reverse

class MyModelMixin(object):
    
    def _get_field_names(self):
        field_names = [field.name for field in self._meta.fields]
        return field_names
    field_names = property(_get_field_names)
    
    def _get_all_field_data(self):
        fields_data = [getattr(self, field) for field in self.field_names]
        return fields_data
    all_field_data = property(_get_all_field_data)
    

class Address(MyModelMixin, models.Model):
    street = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    
    def __unicode__(self):
        return self.street + ' ' + self.city + ', ' + self.state
    

class Person(MyModelMixin, models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    home_address = models.ForeignKey(Address, blank=True, null=True)
    
    class Meta:
        ordering = ['last_name']
    
    def _get_full_name(self):
        return self.first_name + ' ' + self.last_name
    full_name = property(_get_full_name)
    
    def __unicode__(self):
        return self.last_name + ', ' + self.first_name

class Patient(Person):
    pcp = models.ForeignKey('Doctor', blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse('RapidReferral:patient_detail', kwargs={'patient_id': self.id})
    
class Doctor(Person):
    patients = models.ManyToManyField(Patient, blank=True, null=True)
    specialties = models.ManyToManyField('Specialty')
    #maybe add house_calls bool. if so move home_address to person model
    
    def get_absolute_url(self):
        return reverse('RapidReferral:doctor_detail', kwargs={'doctor_id': self.id})
    
class Office(MyModelMixin, models.Model):
    name = models.CharField(max_length=50, blank=True)
    address = models.ForeignKey(Address)
    doctors = models.ManyToManyField(Doctor)
    
    class Meta:
        ordering = ['name']
    
    def get_absolute_url(self):
        return reverse('RapidReferral:office_detail', kwargs={'office_id': self.id})
    
    def __unicode__(self):
        return self.name
    
    
    
class Specialty(MyModelMixin, models.Model):
    specialty = models.CharField(max_length=50, primary_key=True)
    
    class Meta:
        ordering = ['specialty']
    
    def __unicode__(self):
        return self.specialty
    
class Appointment(MyModelMixin, models.Model):
    patient = models.ForeignKey(Patient)
    specialty = models.ForeignKey(Specialty)
    office = models.ForeignKey(Office)
    doctor = models.ForeignKey(Doctor)
    time = models.DateTimeField()
    
    def get_absolute_url(self):
        return reverse('RapidReferral:appointment_detail', kwargs={'appointment_id' : self.id})
                
class OfficeFilterForm(forms.Form):
    specialty = forms.ModelChoiceField(queryset=Specialty.objects.all(), required=False)
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(), required=False)
    #address: to be added to filter by address and proximity
    #proximity: to be added.
    
   
    
                
class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        
class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ['home_address'] 
 
class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__' #['patient', 'doctor', 'specialty', 'office', 'time']
        
class OfficeForm(forms.ModelForm):
    class Meta:
        model = Office
        fields = '__all__'
        
# class AppointmentFilterForm(AppointmentForm):
    # def __init__(self, *args, **kwargs):
        # super(AppointmentFilterForm, self).__init__(*args, **kwargs)
        # self.fields['time2'] = forms.fields.DateTimeField()
        # del self.fields['patient']
        
        # #for k, v in self.fields.items():
            # v.required = False
               
    # class Meta(AppointmentForm.Meta):
        # pass
        
class AppointmentFilterForm(forms.Form):       
    patient = forms.ModelChoiceField(queryset=Patient.objects.all(), required=False)
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(), required=False)
    specialty = forms.ModelChoiceField(queryset=Specialty.objects.all(), required=False)
    office = forms.ModelChoiceField(queryset=Office.objects.all(), required=False)
    time = forms.DateTimeField(required=False)
    time2 = forms.DateTimeField(required=False)
        
        
        
        
        
        
        
        

RapidReferral/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.core import serializers
from RapidReferral.models import Doctor, DoctorForm, Patient, PatientForm, Office, OfficeForm, OfficeFilterForm, Appointment, AppointmentForm, AppointmentFilterForm
import operator
import datetime
import pdb

def index(request):
    #needs a real index page
    return HttpResponse("RR index page")
 
def doctors(request, format = 'HTML'):
    d_list = Doctor.objects.all()
    if request.GET:
        form = DoctorFilterForm(request.GET)
        sp_filter = form.cleaned_data['specialty']
        o_filter = form.cleaned_data['office']
        if form.is_valid:
            if sp_filter:
                d_list = d_list.filter(specialties__specialty=sp_filter)
            
            
        
        
    doctor_list = Doctor.objects.order_by('last_name')
    context = {'object_list': doctor_list}
    return render(request, 'RapidReferral/doctor_list.html', context)
 
def doctor_detail(request, doctor_id):
    doctor = get_object_or_404(Doctor, pk=doctor_id)
    context = {'doctor': doctor}
    return render(request, 'RapidReferral/doctor_detail.html', context)
    
def doctor_entry(request):
    doctor_form = DoctorForm()
    context = {'form': doctor_form}
    return render(request, 'RapidReferral/base_form.html', context)
    
def patients(request):
    patient_list = Patient.objects.order_by('last_name')
    context = {'object_list': patient_list}
    return render(request, 'RapidReferral/patient_list.html', context)

def patient_detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    context = {'patient': patient}
    return render(request, 'RapidReferral/patient_detail.html', context)
    
def patient_entry(request):
    patient_form = PatientForm()
    context = {'form': patient_form}
    return render(request, 'RapidReferral/base_form.html', context)

def offices(request, format = 'HTML'):
    o_list = Office.objects.all()
    if request.GET:
        form = OfficeFilterForm(request.GET)
        if form.is_valid():
            sp_filter = form.cleaned_data['specialty']            
            d_filter = form.cleaned_data['doctor']
            if form.cleaned_data['specialty']:
                o_list = o_list.filter(doctors__specialties__specialty=sp_filter)
            if form.cleaned_data['doctor']:
                o_list = o_list.filter(doctors=d_filter)
    else:
        form = OfficeFilterForm()
        
    context = {'object_list': o_list, 'form': form}
    if format == 'HTML':
        return render(request, 'RapidReferral/base_list_table_filtered.html', context)
    elif format == 'JSON':
        return HttpResponse(serializers.serialize('json', o_list))

def office_detail(request, office_id):
    office = get_object_or_404(Office, pk=office_id)
    context = {'office': office}
    return render(request, 'RapidReferral/office_detail.html', context)
    
def office_entry(request):
    
    if request.method == 'POST':
        form = OfficeForm(request.POST)
        if form.is_valid():     
            new_office = form.save()
            return redirect(new_office)                      
    else:
        form = OfficeForm()
    context = {'form': form}
    return render(request, 'RapidReferral/base_form.html', context)

def specialties(request):
    pass
    
def specialty_detail(request, specialty_id):
    pass
    
def appointments(request):
    qs = Appointment.objects.all()
    if request.GET:
        form = AppointmentFilterForm(request.GET)
        if form.is_valid():
        
            start_date_time, end_date_time = form.cleaned_data['time'], form.cleaned_data['time2']
            if start_date_time:
                qs = qs.filter(time__gt=start_date_time)
            if end_date_time:
                qs = qs.filter(time__lt=end_date_time)
               
            for field_name, field_value in form.cleaned_data.iteritems():
                if field_value and 'time' not in field_name:
                    qs = qs.filter(**{field_name:field_value})
    else:
        form = AppointmentFilterForm()
    appointment_list = qs.order_by('time')
    context = {'object_list': appointment_list, 'form': form}
    return render(request, 'RapidReferral/appointment_list_table_filtered.html', context)
    
def appointment_detail(request, appointment_id, appointment_context=None):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    context = {'appointment': appointment}
    return render(request, 'RapidReferral/appointment_detail.html', context)
    
def appointment_entry(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():     
            new_appointment = form.save()
            
            d = new_appointment.doctor
            p = new_appointment.patient
            if not p.doctor_set.filter(id=d.id).count:
                d.patients.add(p)
                            
            return redirect(new_appointment)      
            #return redirect('appointment_detail', new_appointment.id)  
                
    else:
        form = AppointmentForm()
    context = {'form': form}
    return render(request, 'RapidReferral/appointment_form.html', context)

# def json_offices(request):
    # o_list = Office.
        
#def referral_search(request):
    
#def referral_result(request):

RapidReferral/templates/RapidReferral/appointment_detail.html
{% extends 'RapidReferral/base_detail.html' %}

{% block detail %}

{% if appointment %}
<h1>Appointment:</h1>
<p>
<a href="{% url 'RapidReferral:appointments' %}?patient={{ appointment.patient.id }}">{{ appointment.patient.full_name }}</a>
will go to 
<a href="{% url 'RapidReferral:appointments' %}?office={{ appointment.office.id }}">{{ appointment.office }}</a>
to see 
<a href="{% url 'RapidReferral:appointments' %}?doctor={{ appointment.doctor.id }}">Dr. {{ appointment.doctor.full_name }}</a> 
for
{{ appointment.specialty }}
on 
{{ appointment.time }}</p>

<p class="helptext">Click on a link to view all appointments for that item</p>

{% else %}
<h1>no appt found with that ID</h1>

{% endif %}

{% endblock %}

RapidReferral/templates/RapidReferral/appointment_form.html
{% extends 'RapidReferral/base_form.html' %}
{% block script %}
{% endblock %}



{% block footer %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'RapidReferral/jquery.datetimepicker.css' %}"/>
<script src="{% static 'RapidReferral/jquery.datetimepicker.js' %}"></script>
<script>
jQuery('#id_time').datetimepicker({
    format:'Y-m-d h:m',
    });
 </script>
{% endblock %}

RapidReferral/templates/RapidReferral/appointment_list.html
{% extends 'RapidReferral/base_list_table.html' %}
{% if context %}
<h2>Appointments for {{ appointment_context }}:</h2>
{% endif %}   

RapidReferral/templates/RapidReferral/appointment_list_table_filtered.html
{% extends 'RapidReferral/base_list_table_filtered.html' %}


{% load staticfiles %}

{% block links %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'RapidReferral/jquery.datetimepicker.css' %}"/>
{% endblock %}

{% block no_data %}<h1>No appointments found with those criteria</h1>{% endblock %}

{% block footer %}
{{ block.super }}

<script src="{% static 'RapidReferral/jquery.datetimepicker.js' %}"></script>
<script>
jQuery('#id_time').datetimepicker({
    format:'Y-m-d h:m',
    });
jQuery('#id_time2').datetimepicker({
    format:'Y-m-d h:m',
    });
</script>

{% endblock %}

RapidReferral/templates/RapidReferral/base.html
{% load staticfiles %}

<!DOCTYPE html>
<hmtl>
<head>
{% block head %}
    <title>{% block title %}RapidReferral{% endblock %}</title>
    
    {% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'RapidReferral/dropdown-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'RapidReferral/dropdown-menu-skin.css' %}">
    {% endblock %}   
        
    <style>
    {% block style %}

    table {
        border-left: 1px solid #B0CCFF;
        border-bottom: 1px solid #B0CCFF;
        border-radius: 10px;
        overflow: hidden;
    }
    
        
    th, td {
        border-top: 1px solid #B0CCFF;
        border-right: 1px solid #B0CCFF;
    }
    
    table {
        border-spacing: 0;
    }

    th {
        background-color: #387BA6;
        color: #ffffff;
    }

    td {
        padding: 3px 6px 3px 6px;
    }

    tr.alt td {
        color: #000000;
        background-color: #addfff;
    }

    p.helptext {
        font-style: italic;
        color: #91ADBF;
    }

    
    a, a:active { 
        text-decoration: none 
    }

    {% endblock %}
    </style>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js">{% block script %}{% endblock %}</script>

{% endblock %}
</head>

<body>
{% block menu %}


<ul id="navigation" class="dropdown-menu dropdown-menu-skin">
    <li><a href="#">Patients</a>
        <ul>
            <li><a href="{% url 'RapidReferral:patients' %}">Patient list</a></li>
            <li><a href="{% url 'RapidReferral:patient_entry' %}">Create patient</a></li>
        </ul>
    </li>
    <li><a href="#">Doctors</a>
        <ul>
            <li><a href="{% url 'RapidReferral:doctors' %}">Doctor list</a></li>
            <li><a href="{% url 'RapidReferral:doctor_entry' %}">Create doctor</a></li>
        </ul>
    </li>
    <li><a href="#">Offices</a>
        <ul>
            <li><a href="{% url 'RapidReferral:offices' %}">Office list</a></li>
            <li><a href="{% url 'RapidReferral:office_entry' %}">Create office</a></li>
        </ul>
    </li>
    <li><a href="#">Appointments</a>
        <ul>
            <li><a href="{% url 'RapidReferral:appointments' %}">Appointment list</a></li>
            <li><a href="{% url 'RapidReferral:appointment_entry' %}">Create appointment</a></li>
        </ul>
    </li>
</ul>

{% endblock %}

{% block body %}

{% endblock %}


{% block menu-footer %}

<script type="text/javascript" src="{% static 'RapidReferral/dropdown-menu.min.js' %}"></script>

<script type="text/javascript">
$(function() {
    $('#navigation').dropdown_menu({
        sub_indicators : true,
        drop_shadows : true,
        close_delay : 500
    });
});
</script>
{% endblock %}

{% block footer %}{% endblock %}

</body>

</html>

RapidReferral/templates/RapidReferral/base_form.html
{% extends 'RapidReferral/base.html' %}

{% block body %}
<form method="post">
    <table>
        {% csrf_token %}
        {{ form }}
        <tr><td><input type="submit" value="Confirm"></td></tr>
    </table>
</form>
{% endblock %}

RapidReferral/templates/RapidReferral/base_list.html
{% extends 'RapidReferral/base.html' %}

{% block body %}
{% block list %}
    {% if object_list %}
        <ul>
        {% for object in object_list %}
            {% block list_item %}{% endblock %}
        {% endfor %}
        </ul>
    {% else %}
        <p>No objects found.</p>
    {% endif %}
{% endblock %}
{% endblock %}

RapidReferral/templates/RapidReferral/base_list_table_filtered.html
{% extends 'RapidReferral/base_list_table.html' %}

{% load staticfiles %}

{% block links %}
{{ block.super }}

<link rel="stylesheet" type="text/css" href="{% static 'RapidReferral/filterTable.css' %}">

{% endblock %}

{% block body %}
{{ block.super }}
<form method="get">
    <table class="filterTable">
    <tr><th colspan=2 class="filterHead">Filter appointments by:</th></tr>
    {{ form }}
    <tr><td colspan=2><input type="submit" value="Filter" class="filterButton"></td></tr>
    </table>
</form>
{% endblock %}

RapidReferral/templates/RapidReferral/doctor_detail.html
{% extends 'RapidReferral/base_detail.html' %}

{% block detail %}

{% if doctor %}
    <h1>Dr. {{ doctor.full_name }}</h1>
    <h3>Specialties:</h3>
        <ul>
        {% for specialty in doctor.specialties.all %}
            <li>{{ specialty }}</li>
        {% endfor %}
        </ul>
    <h3>Offices:</h3>
        <ul>
        {% for office in doctor.office_set.all %}
            <li><a href="{% url 'RapidReferral:office_detail' office.id %}">{{ office }}</a></li>
        {% endfor %}
        </ul>
{% else %}
    <p>No doctor found with that ID.</p>
{% endif %}

{% endblock %}

RapidReferral/templates/RapidReferral/doctor_list.html
{% extends 'RapidReferral/base_list.html' %}

{% block list_item %}
    <li><a href="{% url 'RapidReferral:doctor_detail' object.id %}">{{ object.full_name }}</a> 
    / Primary care patients: {{ object.patient_set.count }}
    / Specialty Patients: {{ object.patients.count }}</li>
{% endblock %}

RapidReferral/templates/RapidReferral/office_list.html
{% extends 'RapidReferral/base_list.html' %}

{% block list_item %}
    <li><a href="{% url 'RapidReferral:office_detail' object.id %}">{{ object }}</a></li>
{% endblock %}

RapidReferral/templates/RapidReferral/patient_detail.html
{% extends 'RapidReferral/base_detail.html' %}

{% block detail %}

{% if patient %}
    <h1>{{ patient.full_name }}</h1>
    <h3>Primary Care physician:
    {% if patient.pcp %}
        <a href="{% url 'RapidReferral:doctor_detail' patient.pcp.id %}">{{ patient.pcp.full_name }}</a></li>
    {% else %}
        none
    {% endif %}
    </h3>
{% else %}
    <p>No patient found with that ID.</p>
{% endif %}

{% endblock %}

RapidReferral/templates/RapidReferral/patient_list.html
{% extends 'RapidReferral/base_list.html' %}

{% block list_item %}
    <li><a href="{% url 'RapidReferral:patient_detail' object.id %}">{{ object.full_name }}</a></li>
{% endblock %}        